/**
 * V2 data layer. The v1 endpoint modules are already fully typed against the
 * backend views — v2 re-exports them plus the shared client types it needs.
 */
export * from "../api/endpoints";
export * from "../api/stream";
export type {
  Agent,
  Alert,
  Approval,
  AuditRow,
  CalibrationReport,
  CalibrationBucket,
  ChatResponse,
  ControlResult,
  DecisionDrilldown,
  Equity,
  EvaluationRecord,
  Executive,
  Gates,
  Gate,
  GlobalEvent,
  Graduation,
  Health,
  HypothesisDetail,
  KnowledgeRow,
  KnowledgeSummary,
  ModelVersion,
  Opportunity,
  Order,
  PlatformEvent,
  Pnl,
  PnlBucket,
  Portfolio,
  Position,
  Regime,
  RiskState,
  RiskTransition,
  SettingsView,
  StrategyRow,
  StreamFrame,
  Unavailable,
  KernelBookOfRecord,
  KernelCash,
  KernelEventBackbone,
  KernelFill,
  KernelFinding,
  KernelHealth,
  KernelInvariants,
  KernelIborCash,
  KernelIborPosition,
  KernelOrder,
  KernelOrderDetail,
  KernelOutbox,
  KernelPosition,
  KernelPositions,
  KernelReconciliation,
  KernelReconciliationRun,
  KernelReservation,
  KernelCashRow,
  KernelSafetyState,
} from "../api/types";
